In [57]:
import torch
from operations import FConv2d,FBatchnorm2d,img_to_spatial,\
img_to_freq,get_mean_var_fourier,get_mean_var

conv = FConv2d(3,1,3,shift_output = False)
x = torch.randn(1,3,5,5)
x1 = x
print(img_to_spatial(conv(img_to_freq(x)),kernel_size=3))
print(conv.forward_correct(x1))


tensor([[[[ 1.4629, -1.6180,  0.5108],
          [ 0.2024, -0.3528,  0.4240],
          [ 1.0820,  1.0805, -0.9200]]]], grad_fn=<SliceBackward>)
tensor([[[[ 1.4629, -1.6180,  0.5108],
          [ 0.2024, -0.3528,  0.4240],
          [ 1.0820,  1.0805, -0.9200]]]], grad_fn=<ThnnConv2DBackward>)


In [58]:
conv = FConv2d(3,1,5,shift_output = True)
x = torch.randn(1,3,5,5)
x1 = torch.nn.functional.pad(input=x, pad=(2, 2, 2, 2), mode='circular')

print(img_to_spatial(conv(img_to_freq(x))))
print(conv.forward_correct(x1))

tensor([[[[ 0.5297, -2.8165,  2.5488,  0.3453, -3.7369],
          [ 1.2941, -1.7941, -0.7160, -2.0340, -0.5189],
          [-1.5670, -0.0219,  1.5823, -1.8955,  2.4711],
          [-2.1797,  2.6697, -1.3972,  2.9924, -1.7464],
          [ 0.9626, -1.1231, -2.4438,  1.8657, -2.4362]]]],
       grad_fn=<CopySlices>)
tensor([[[[ 0.5297, -2.8165,  2.5488,  0.3453, -3.7369],
          [ 1.2941, -1.7941, -0.7160, -2.0340, -0.5189],
          [-1.5670, -0.0219,  1.5823, -1.8955,  2.4711],
          [-2.1797,  2.6697, -1.3972,  2.9924, -1.7464],
          [ 0.9626, -1.1231, -2.4438,  1.8657, -2.4362]]]],
       grad_fn=<MkldnnConvolutionBackward>)


In [59]:
batchnorm = FBatchnorm2d(channels=3)

xorg = torch.randn(4,3,5,5)
x = img_to_freq(xorg)
y = batchnorm(x)

print(get_mean_var_fourier(y))
print(get_mean_var(xorg))

(tensor([ 0.1601,  0.0292, -0.0580], grad_fn=<MeanBackward1>), tensor([0.8371, 0.9074, 1.1191], grad_fn=<MeanBackward1>))
(tensor([ 0.1583,  0.0292, -0.0594]), tensor([0.8054, 0.8868, 1.1536]))
